# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'OvaryIQ' do

use_frameworks!

#Usage:- KeyBoard Management
pod 'IQKeyboardManagerSwift'

pod 'SwiftLint'

end
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
